apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: xgolis/wac-tg-jv
  newName: xgolis/wac-tg-jv
  newTag: main.20240525.1301  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
- name: xgolis/wac-tg-jv-backend
  newName: xgolis/wac-tg-jv-backend
  newTag: main.20240525.1511

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: wac-tg-jv
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  wac-tg-jv
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1
