apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
 name: wac-tg-jv-repo # v spoločnom klastri je nasadených viacero takýchto objektov
 namespace: wac-hospital
spec:
 interval: 1m0s
 ref:
     branch: main
 timeout: 1m0s
 url: https://github.com/xgolis/wac-tg-jv-gitops
