apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

- deployment.yaml
- service.yaml
- configmap.yaml
- http-route.yaml

commonLabels:
  app.kubernetes.io/component: wac-tg-jv-backend
