apiVersion: apps/v1
kind: Deployment
metadata:
  name: wac-tg-jv
spec:
  replicas: 1
  selector:
    matchLabels:
        pod: wac-tg-jv
  template:
    metadata:
      labels:
        pod: wac-tg-jv
    spec:
      containers:
      - name: wac-tg-jv
        image: xgolis/wac-tg-jv
        imagePullPolicy: Always

        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
              memory: "32M"
              cpu: "0.1"
          limits:
              memory: "320M"
              cpu: "0.3"
