apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: wac-tg-jv
spec:
  module-uri: http://wac-tg-jv.wac-hospital/build/ambulance-ufe.esm.js

  navigation:
    - element: wac-tg-jv
      path: wac-tg-jv
      title: Semestralne zadanie tg-jv
      details: Semestralne zadanie xgolis xvlcek
  preload: false
  proxy: true

  hash-suffix: v1alpha1
